version: '3'
services:
    r0:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 1 && sh runscripts/startReplicaYCSB.sh 0'
        

    r1:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 5 && sh runscripts/startReplicaYCSB.sh 1'


    r2:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 7 && sh runscripts/startReplicaYCSB.sh 2'
        
        
    r3:
        image: bftsmart
        restart: always
        command: sh -c 'sleep 9 && sh runscripts/startReplicaYCSB.sh 3'
    


    client:
        image: bftsmart
        command: sh -c 'sleep 15 && sh runscripts/ycsbLoader.sh'

   